services:
  - type: web
    name: cuisine-classification
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --worker-class sync --workers 1 --bind 0.0.0.0:10000 --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
